# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/mkdocs/mkdocs.yml
# See: https://www.mkdocs.org/user-guide/configuration/

site_name: Arduino CLI
site_description: Arduino Command Line Interface
site_url: https://arduino.github.io/ptsolns-cli/

repo_name: arduino/ptsolns-cli
repo_url: https://github.com/arduino/ptsolns-cli
edit_uri: blob/master/docs/

copyright: Copyright 2020 ARDUINO SA (http://www.arduino.cc/)

theme:
  name: material
  logo: img/icon_mac_light.png
  palette:
    primary: teal
    accent: orange

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.twemoji
  - pymdownx.magiclink:
      repo: ptsolns-cli
      repo_url_shorthand: true
      user: arduino
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - installation.md
  - UPGRADING.md
  - getting-started.md
  - command-line-completion.md
  - CONTRIBUTING.md
  - FAQ.md
  - Command reference:
      - ptsolns-cli: commands/ptsolns-cli.md
      - board: commands/ptsolns-cli_board.md
      - board attach: commands/ptsolns-cli_board_attach.md
      - board details: commands/ptsolns-cli_board_details.md
      - board list: commands/ptsolns-cli_board_list.md
      - board listall: commands/ptsolns-cli_board_listall.md
      - board search: commands/ptsolns-cli_board_search.md
      - burn-bootloader: commands/ptsolns-cli_burn-bootloader.md
      - cache: commands/ptsolns-cli_cache.md
      - cache clean: commands/ptsolns-cli_cache_clean.md
      - compile: commands/ptsolns-cli_compile.md
      - completion: commands/ptsolns-cli_completion.md
      - config: commands/ptsolns-cli_config.md
      - config dump: commands/ptsolns-cli_config_dump.md
      - config init: commands/ptsolns-cli_config_init.md
      - config add: commands/ptsolns-cli_config_add.md
      - config delete: commands/ptsolns-cli_config_delete.md
      - config get: commands/ptsolns-cli_config_get.md
      - config remove: commands/ptsolns-cli_config_remove.md
      - config set: commands/ptsolns-cli_config_set.md
      - core: commands/ptsolns-cli_core.md
      - core download: commands/ptsolns-cli_core_download.md
      - core install: commands/ptsolns-cli_core_install.md
      - core list: commands/ptsolns-cli_core_list.md
      - core search: commands/ptsolns-cli_core_search.md
      - core uninstall: commands/ptsolns-cli_core_uninstall.md
      - core update-index: commands/ptsolns-cli_core_update-index.md
      - core upgrade: commands/ptsolns-cli_core_upgrade.md
      - daemon: commands/ptsolns-cli_daemon.md
      - debug: commands/ptsolns-cli_debug.md
      - debug check: commands/ptsolns-cli_debug_check.md
      - lib: commands/ptsolns-cli_lib.md
      - lib deps: commands/ptsolns-cli_lib_deps.md
      - lib download: commands/ptsolns-cli_lib_download.md
      - lib examples: commands/ptsolns-cli_lib_examples.md
      - lib install: commands/ptsolns-cli_lib_install.md
      - lib list: commands/ptsolns-cli_lib_list.md
      - lib search: commands/ptsolns-cli_lib_search.md
      - lib uninstall: commands/ptsolns-cli_lib_uninstall.md
      - lib update-index: commands/ptsolns-cli_lib_update-index.md
      - lib upgrade: commands/ptsolns-cli_lib_upgrade.md
      - monitor: commands/ptsolns-cli_monitor.md
      - outdated: commands/ptsolns-cli_outdated.md
      - sketch: commands/ptsolns-cli_sketch.md
      - sketch archive: commands/ptsolns-cli_sketch_archive.md
      - sketch new: commands/ptsolns-cli_sketch_new.md
      - update: commands/ptsolns-cli_update.md
      - upgrade: commands/ptsolns-cli_upgrade.md
      - upload: commands/ptsolns-cli_upload.md
      - version: commands/ptsolns-cli_version.md
  - gRPC reference:
      - commands: rpc/commands.md
  - configuration.md
  - Integration options: integration-options.md
  - sketch-build-process.md
  - sketch-specification.md
  - sketch-project-file.md
  - library-specification.md
  - platform-specification.md
  - Pluggable discovery specification: pluggable-discovery-specification.md
  - Pluggable monitor specification: pluggable-monitor-specification.md
  - Package index specification: package_index_json-specification.md
  - Guides:
      - Secure boot: guides/secure-boot.md
  - Backward compatibility policy: versioning.md

extra:
  version:
    provider: mike
